import "mocha/mocha.js";
// This is generated by the rollup plugin

import tests from "all-tests";

(window as any).runTests = function() {
    mocha.setup({
        ui: "bdd"
    });

    tests();

    let div = document.createElement("div");
    div.id = "mocha";
    document.body.appendChild(div);
    let runner = mocha.run() as any;

    runner.on("fail", (test, error) => {
        console.log(test, error);
        debugger;
        (window as any).err = error;
        // if (error.message === "Script error. (:0)") {
        //     // weird bug, not sure what causes this.
        //     return;
        // }
        console.log("WHAT THE HELL", test.title);
        (window as any).webkit.messageHandlers.testReporter.postMessage({
            done: false,
            test: test.title,
            error: error.message
        });
    });
    runner.on("pass", test => {
        console.info(test);
        console.log("WHAT THE PASS", test.title);
        (window as any).webkit.messageHandlers.testReporter.postMessage({
            done: false,
            test: test.title
        });
    });

    runner.on("end", () => {
        (window as any).webkit.messageHandlers.testReporter.postMessage({
            done: true
        });
    });
};
window.onload = function() {
    // (window as any).runTests();
};

window.onerror = function(err) {
    (window as any).webkit.messageHandlers.testReporter.postMessage({
        done: false,
        test: "Uncaught error",
        error: String(err)
    });
};
